import os

env = Environment(ENV=os.environ, CPPPATH = ['.', '../../src/shared/vmap', '../../src/framework', '../../dep/include/g3dlite', '../../dep/ACE_wrappers',
	'../../objdir/dep/ACE_wrappers'])

env.Program(target = 'vmap_assembler',
		source = ['vmap_assembler.cpp'],
		LIBS = ['mangosvmaps','g3dlite'],
		LIBPATH = ['../../objdir/src/shared/vmap','../../objdir/dep/src/g3dlite'])

#env.Program(target = 'test',
#		source = ['coordinate_test.cpp'],
#		LIBS = ['mangosvmaps','g3dlite'],
#		LIBPATH = ['../../objdir/src/shared/vmap','../../objdir/dep/src/g3dlite'])
